### ISSUE TITLE
Plugin freezes frequently on code completion

### ISSUE THREAD

**Issue by markschiffner** [overstory/marklogic-intellij-plugin#63]
I am seeing repetitive hanging/freezing on ItelliJ Ultimate 2020.2 using version 1.1.1 of the plugin.
This is making Intellij with the plugin almost unusable (url)

"ApplicationImpl pooled thread 6" prio=0 tid=0x0 nid=0x0 runnable
     java.lang.Thread.State: RUNNABLE

    at java.base@11.0.8/java.util.regex.Pattern.RemoveQEQuoting(Pattern.java:1731)
    at java.base@11.0.8/java.util.regex.Pattern.compile(Pattern.java:1768)
    at java.base@11.0.8/java.util.regex.Pattern.<init>(Pattern.java:1428)
    at java.base@11.0.8/java.util.regex.Pattern.compile(Pattern.java:1068)
    at java.base@11.0.8/java.lang.String.replaceFirst(String.java:2081)
    at org.intellij.xquery.completion.keyword.KeywordCollector.variantsToReplace(KeywordCollector.java:164)
    at org.intellij.xquery.completion.keyword.KeywordCollector.stringPrecedingText(KeywordCollector.java:144)
    at org.intellij.xquery.completion.keyword.KeywordCollector.suggestKeywordsBasedOnParserExpectedKeywords(KeywordCollector.java:137)
    at org.intellij.xquery.completion.keyword.KeywordCollector.getProposedLookUpItems(KeywordCollector.java:76)
    at org.intellij.xquery.completion.XQueryCompletionContributor$1.addCompletions(XQueryCompletionContributor.java:84)
    at com.intellij.codeInsight.completion.CompletionProvider.addCompletionVariants(CompletionProvider.java:32)
    at com.intellij.codeInsight.completion.CompletionContributor.fillCompletionVariants(CompletionContributor.java:155)
    at com.intellij.codeInsight.completion.CompletionService.getVariantsFromContributors(CompletionService.java:76)
    at com.intellij.codeInsight.completion.CompletionResultSet.runRemainingContributors(CompletionResultSet.java:154)
    at com.intellij.codeInsight.completion.CompletionResultSet.runRemainingContributors(CompletionResultSet.java:146)
    at com.intellij.codeInsight.completion.CompletionResultSet.runRemainingContributors(CompletionResultSet.java:142)
    at com.intellij.codeInsight.template.impl.LiveTemplateCompletionContributor$1.addCompletions(LiveTemplateCompletionContributor.java:88)

**Comment by markschiffner** [comment]
[threadDump-20200912-145512.txt](https://github.com/overstory/marklogic-intellij-plugin/files/5391407/threadDump-20200912-145512.txt)
[threadDump-20200912-145517.txt](https://github.com/overstory/marklogic-intellij-plugin/files/5391409/threadDump-20200912-145517.txt)
